name: build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build --build-arg IMAGE=centos:centos6 -t skaji/relocatable-perl -f build/Dockerfile .
      - run: bash build/github-actions.sh linux_amd64_create_artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: linux-amd64
          path: linux-amd64
  linux-ppc64le:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: podman build --build-arg IMAGE=ubi:ubi8 -t skaji/relocatable-perl -f build/Dockerfile .
      - run: bash build/github-actions.sh linux_ppc64le_create_artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: linux-ppc64le
          path: linux-ppc64le

  linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: docker buildx build --platform linux/arm64 --build-arg IMAGE=centos:centos7 -t skaji/relocatable-perl -f build/Dockerfile --load .
      - run: bash build/github-actions.sh linux_arm64_create_artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: linux-arm64
          path: linux-arm64
  darwin-amd64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: sw_vers
      - run: bash build/github-actions.sh mac_prepare_tools
      - run: bash build/github-actions.sh mac_build_perl
      - run: bash build/github-actions.sh mac_create_artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: darwin-amd64
          path: darwin-amd64
